[tools]
"tuist" = "4.39.1"
"swiftlint" = "0.57.0"
"swiftformat" = "0.54.5"
"swift" = "5.9.2"
"pnpm" = "9.15.4"
"node" = "22.13.1"
"podman" = "4.9.3"
"git-cliff" = "2.4.0"

[plugins]
swift = "https://github.com/fcrespo82/asdf-swift"
podman = "https://github.com/tvon/asdf-podman.git"
