[tools]
tuist = "4.76.1"
swiftlint = "0.59.1"
swiftformat = "0.56.4"
pnpm = "10.17.0"
node = "24.8.0"
git-cliff = "2.9.1"
elixir = "1.18.4-otp-27"
erlang = "27.3.4"
"npm:prettier" = "3.6.2"
flyctl = "0.3.152"

[hooks]
postinstall = "mise run install"

[settings]
experimental = true
