[tools]
tuist = "4.110.0"
swiftlint = "0.59.1"
swiftformat = "0.56.4"
pnpm = "10.24.0"
node = "24.11.1"
git-cliff = "2.9.1"
elixir = "1.19.4"
erlang = "28.2"
"npm:prettier" = "3.7.3"
flyctl = "0.3.152"

[hooks]
postinstall = "mise run install"

[settings]
experimental = true
