[tools]
tuist = "4.142.0"
swiftlint = "0.63.2"
swiftformat = "0.59.1"
pnpm = "10.29.2"
node = "24.13.1"
git-cliff = "2.9.1"
elixir = "1.19.5"
erlang = "28.3.1"
"npm:prettier" = "3.8.1"
flyctl = "0.3.152"

[hooks]
postinstall = "mise run install"

[settings]
experimental = true
