[tools]
tuist = "4.95.0"
swiftlint = "0.59.1"
swiftformat = "0.56.4"
pnpm = "10.20.0"
node = "24.11.0"
git-cliff = "2.9.1"
elixir = "1.19.1"
erlang = "28.1.1"
"npm:prettier" = "3.6.2"
flyctl = "0.3.152"

[hooks]
postinstall = "mise run install"

[settings]
experimental = true
