[tools]
tuist = "4.130.2"
swiftlint = "0.63.1"
swiftformat = "0.58.7"
pnpm = "10.28.1"
node = "24.13.0"
git-cliff = "2.9.1"
elixir = "1.19.5"
erlang = "28.3.1"
"npm:prettier" = "3.8.1"
flyctl = "0.3.152"

[hooks]
postinstall = "mise run install"

[settings]
experimental = true
