[tools]
tuist = "4.118.1"
swiftlint = "0.59.1"
swiftformat = "0.56.4"
pnpm = "10.26.2"
node = "24.12.0"
git-cliff = "2.9.1"
elixir = "1.19.4"
erlang = "28.3"
"npm:prettier" = "3.7.4"
flyctl = "0.3.152"

[hooks]
postinstall = "mise run install"

[settings]
experimental = true
