[tools]
tuist = "4.123.0"
swiftlint = "0.63.0"
swiftformat = "0.58.7"
pnpm = "10.28.0"
node = "24.13.0"
git-cliff = "2.9.1"
elixir = "1.19.5"
erlang = "28.3.1"
"npm:prettier" = "3.7.4"
flyctl = "0.3.152"

[hooks]
postinstall = "mise run install"

[settings]
experimental = true
